apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: web-services
  name: nginx-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/www/alexraustin/
