apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: alice
    name: ollama-pvc
  hostPath:
    path: /var/lib/ollama/
