apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: minecraft 
  name: our-deployment
  labels:
    app: fabric-ours
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fabric-ours
  template:
    metadata:
      labels:
        app: fabric-ours
    spec:
      hostNetwork: true
      containers:
      - name: minecraft-ours
        image: ghcr.io/araustin01/mir-registry:mc-smp
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_PTRACE
              - SYS_ADMIN
              - REPTYR
          seccompProfile:
            type: Unconfined
        env:
        - name: TZ
          value: "America/New_York"
        ports:
        - containerPort: 25566
        - containerPort: 19133
        volumeMounts:
        - mountPath: /minecraft
          name: minecraft-our-storage
      volumes:
      - name: minecraft-our-storage
        hostPath:
          path: /shared/minecraft/ours
          type: Directory
      imagePullSecrets:
      - name: ghcr-secret
