apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: minecraft 
  name: plus-deployment
  labels:
    app: fabric-plus
spec:
  replicas: 1 # Number of desired Pods
  selector:
    matchLabels:
      app: fabric-plus
  template:
    metadata:
      labels:
        app: fabric-plus
    spec:
      hostNetwork: true
      containers:
      - name: minecraft-plus
        image: ghcr.io/araustin01/mir-registry:mc-smp
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_PTRACE
              - SYS_ADMIN
              - REPTYR
          seccompProfile:
            type: Unconfined
        resources:
          requests:
            memory: "10Gi"  # Guarantee 10GB is available for this pod
            cpu: "4"
        tty: true
        stdin: true
        env:
        - name: TZ
          value: "America/New_York"
        ports:
        - containerPort: 25567
        - containerPort: 19134
        volumeMounts:
        - mountPath: /minecraft
          name: minecraft-plus-storage
      volumes:
      - name: minecraft-plus-storage
        hostPath:
          path: /shared/minecraft/plus
          type: Directory
      imagePullSecrets:
      - name: ghcr-secret
