apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: alice
  name: ollama-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: microk8s-hostpath
