apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  labels:
    app: minecraft
spec:
  type: LoadBalancer
  selector:
    app: minecraft
  ports:
  - name: minecraft-smp
    protocol: TCP
    port: 25565
    targetPort: 25565
  # Add more ports as needed
