apiVersion: v1
kind: Service
metadata:
  namespace: web-services
  name: outline-proxy
spec:
  type: LoadBalancer
  selector:
    app: outline-server
  ports:
    - name: management
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: proxy-tcp
      port: 8443
      targetPort: proxy-tcp
      protocol: TCP
    - name: proxy-udp
      port: 8443
      targetPort: proxy-udp
      protocol: UDP